# load library
library(dplyr)
library(readr)
library(tidyr)

# Load DMart dataset
df <- read.csv("D:\\Jahanvi\\COEP\\SEM2\\R\\Assignment\\Clean Dmart sales data.csv")
head(df) # It shows first 6 entry of each column

# View Column name
colnames(df)  # Total 28 column present
nrow(df)  # Total 24992 rows
str(df)




# Question 1: Top 5 Profitable Product Name:

# For top 5 profitable product name I have to clean only two specific column "MRP" and  "Discount Price"
# Perform cleaning
df1 <- df %>%
  mutate(
    MRP = ifelse(MRP == "" | MRP =="NA", NA,MRP),
    Discount.Price = ifelse(Discount.Price == "" | Discount.Price =="NA", NA,Discount.Price)
  )
df2 <- df1 %>% distinct()
df_clean <- df2 %>% drop_na(MRP,Discount.Price)
nrow(df_clean)  # Total rows after cleaning: 24992

# Convert to numeric column
df_clean$MRP <- as.numeric(df_clean$MRP)
df_clean$Discount.Price <- as.numeric(df_clean$Discount.Price)

# Create Profit column
df_clean <- df_clean %>%
  mutate(Profit = MRP - Discount.Price)

# Find top 5 profitable product name
top5 <- df_clean %>%
  group_by(Product.Name) %>%
  summarise(Total.Profit = sum(Profit,na.rm = TRUE)) %>%
  arrange(desc(Total.Profit)) %>%
  head(5)
print(top5)






# Question 2: Visual Representation of  Top 5 Profitable Product using Bar Chart

library(stringr)
wrapped_names <- str_wrap(top5$Product.Name, width = 10)
bp <- barplot(
  top5$Total.Profit, 
  names.arg = wrapped_names, 
  main = "Top 5 Profitable Products", 
  col = "red", 
  ylab = "Total Profit", 
  xlab ="Product Name")






# Question 3: Unit sold by Product Name

# I don't have unit sold column, but have Total Order Value and Discount Price Column
# Unit Sold = total Order Value / Discount Price

df_clean$Total.Order.Value = as.numeric(df_clean$Total.Order.Value)
df_clean$Discount.Price = as.numeric(df_clean$Discount.Price)

df_units <- df_clean %>%
  mutate(
    Units.Sold = Total.Order.Value / Discount.Price
  ) %>%
  group_by(Product.Name) %>%
  summarise(Total.Units.Sold = sum(Units.Sold,na.rm = TRUE)) %>%
  arrange(desc(Total.Units.Sold))

print(df_units)
print(df_units, n=22)








# Question 4: Visual Representation of Unit wise top 7 Selling Product using Pie Chart


top7_units <- df_units %>%
  arrange(desc(Total.Units.Sold)) %>%
  head(7)

print(top7_units)

pie(top7_units$Total.Units.Sold, 
    labels = top7_units$Product.Name, 
    main = "Pie Chart for Top 7 Selling Products", 
    col = rainbow(7))










# Question 5: Revenue generated by different Marketing and Advertisement

library(tidyverse)
revenue_by_marketing <- df %>%
  mutate(
    Total_Revenue = as.numeric(trimws(Total.Order.Value))
  ) %>%
  filter(
    Order.Status %in% c("Shipping","Delivered"),
    !is.na(Total_Revenue)
  ) %>%
  group_by(
    Marketing.Advertisement
  ) %>%
  summarise(
    Total_Revenue = sum(Total_Revenue)
  ) %>%
  arrange(desc(Total_Revenue))

print("Revenue Generated by Marketing/Advertisement Channel:")
print(revenue_by_marketing)






# Question 6: Visual representation of Total revenue generated by Marketing / Advertisement using Pie Chart

pie(revenue_by_marketing$Total_Revenue,
    labels = revenue_by_marketing$Marketing.Advertisement,
    main = "Revenue generated by Marketing/Advertisement")
  

